"""
PDF page generation functions.

This module provides functions for generating individual pages of the PDF report.
"""

import logging
from pathlib import Path
from typing import Dict, List, Tuple

from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph

try:
    from PIL import Image

    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False

from chromaspec.analyzers import (
    get_analogous_colors,
    get_complementary_color,
    get_contrast_ratio,
    get_wcag_rating,
)
from chromaspec.converters import hex_to_rgb, rgb_to_cmyk, rgb_to_hsl
from chromaspec.utils.constants import IMAGE_EXTENSIONS, ColorConstants, PDFLayout

logger = logging.getLogger(__name__)


def draw_header(pdf, width: float, height: float) -> None:
    """
    Draw a minimal header following Swiss typographic principles.

    Args:
        pdf: The canvas object.
        width: Page width.
        height: Page height.
    """
    # Minimal header: thin gray rule with small label
    pdf.setStrokeGray(0.7)  # Light gray
    pdf.setLineWidth(PDFLayout.TABLE_BORDER_WIDTH)
    pdf.line(
        PDFLayout.MARGIN,
        height - PDFLayout.MARGIN,
        width - PDFLayout.MARGIN,
        height - PDFLayout.MARGIN,
    )

    # Small ALL-CAPS metadata label
    pdf.setFont(PDFLayout.PRIMARY_FONT, PDFLayout.METADATA_SIZE)
    pdf.setFillGray(0.5)  # Medium gray
    pdf.drawString(
        PDFLayout.MARGIN,
        height - PDFLayout.MARGIN + PDFLayout.GRID_UNIT * 0.5,
        "CHROMASPEC ANALYSIS REPORT",
    )


def draw_footer(pdf, width: float, page_number: int) -> None:
    """
    Draw a minimal footer with systematic alignment.

    Args:
        pdf: The canvas object.
        width: Page width.
        page_number: Current page number.
    """
    # Thin gray rule
    pdf.setStrokeGray(0.7)
    pdf.setLineWidth(PDFLayout.TABLE_BORDER_WIDTH)
    pdf.line(
        PDFLayout.MARGIN, PDFLayout.MARGIN, width - PDFLayout.MARGIN, PDFLayout.MARGIN
    )

    # Small metadata text in gray
    pdf.setFont(PDFLayout.PRIMARY_FONT, PDFLayout.FOOTER_SIZE)
    pdf.setFillGray(0.5)
    pdf.drawString(
        PDFLayout.MARGIN,
        PDFLayout.MARGIN - PDFLayout.GRID_UNIT * 0.8,
        "Generated by ChromaSpec",
    )
    pdf.drawRightString(
        width - PDFLayout.MARGIN,
        PDFLayout.MARGIN - PDFLayout.GRID_UNIT * 0.8,
        f"Page {page_number}",
    )


def draw_cover_page(
    pdf,
    input_path: Path,
    color_categories: Dict[str, List[Tuple[str, float]]],
    width: float,
    height: float,
) -> None:
    """
    Draw the cover page with image preview and summary.

    Args:
        pdf: The canvas object.
        input_path: Path to the input image file.
        color_categories: Dictionary with color categories.
        width: Page width.
        height: Page height.
    """
    # Title - flush left
    pdf.setFont(PDFLayout.PRIMARY_FONT_BOLD, PDFLayout.TITLE_SIZE)
    pdf.setFillColor("black")
    title = "ChromaSpec"
    pdf.drawString(PDFLayout.MARGIN, height - 1 * PDFLayout.MARGIN, title)

    # Subtitle with filename - flush left
    pdf.setFont(PDFLayout.PRIMARY_FONT, PDFLayout.SECTION_SIZE)
    pdf.setFillColor("gray")
    subtitle = f"Color analysis for: {input_path.name}"
    pdf.drawString(PDFLayout.MARGIN, height - 1.4 * PDFLayout.MARGIN, subtitle)

    # Draw the image if it's an image file (not SVG)
    y_after_image = height - 1.8 * PDFLayout.MARGIN
    if input_path.suffix.lower() in IMAGE_EXTENSIONS and PIL_AVAILABLE:
        try:
            with Image.open(input_path) as img:
                # Calculate image dimensions to fit on page
                max_img_width = width - 2 * PDFLayout.MARGIN
                max_img_height = 4 * PDFLayout.MARGIN

                img_width, img_height = img.size
                aspect_ratio = img_width / img_height

                if img_width > max_img_width:
                    img_width = max_img_width
                    img_height = img_width / aspect_ratio

                if img_height > max_img_height:
                    img_height = max_img_height
                    img_width = img_height * aspect_ratio

                # Flush right - image aligned to right margin
                x_pos = width - PDFLayout.MARGIN - img_width
                y_pos = height - 2 * PDFLayout.MARGIN - img_height

                # Draw image
                pdf.drawImage(
                    str(input_path),
                    x_pos,
                    y_pos,
                    width=img_width,
                    height=img_height,
                    preserveAspectRatio=True,
                )
                y_after_image = y_pos - 0.5 * PDFLayout.MARGIN
        except Exception as e:
            logger.warning(f"Could not load image for cover page: {e}")
            pass

    # Concept paragraph
    from reportlab.lib.units import cm

    y_after_image -= 0.3 * PDFLayout.MARGIN

    concept_text = (
        "ChromaSpec extracts and analyzes dominant colors from images and SVG files, "
        "classifying them by hue and providing comprehensive color information for design workflows."
    )

    style = ParagraphStyle(
        "Concept",
        fontName=PDFLayout.PRIMARY_FONT,
        fontSize=12,
        leading=14.4,
        alignment=TA_LEFT,
        textColor="black",
    )

    para = Paragraph(concept_text, style)
    para_width = 10 * cm
    para_height = para.wrap(para_width, height)[1]
    para.drawOn(pdf, PDFLayout.MARGIN, y_after_image - para_height)

    y_after_image -= para_height + 0.5 * PDFLayout.MARGIN

    # Summary statistics
    total_red = len(color_categories["red"])
    total_green = len(color_categories["green"])
    total_blue = len(color_categories["blue"])
    total_colors = total_red + total_green + total_blue

    pdf.setFont(PDFLayout.PRIMARY_FONT_BOLD, 14)
    pdf.setFillColor("black")
    pdf.drawString(PDFLayout.MARGIN, y_after_image, "Color Summary")

    pdf.setFont(PDFLayout.PRIMARY_FONT, 12)
    y_after_image -= 0.4 * PDFLayout.MARGIN
    pdf.drawString(
        PDFLayout.MARGIN, y_after_image, f"Total colors extracted: {total_colors}"
    )
    y_after_image -= 0.3 * PDFLayout.MARGIN
    pdf.setFillGray(0.2)  # Dark gray for red category
    pdf.drawString(PDFLayout.MARGIN, y_after_image, f"Red colors:   {total_red}")
    y_after_image -= 0.3 * PDFLayout.MARGIN
    pdf.setFillGray(0.5)  # Medium gray for green category
    pdf.drawString(PDFLayout.MARGIN, y_after_image, f"Green colors: {total_green}")
    y_after_image -= 0.3 * PDFLayout.MARGIN
    pdf.setFillGray(0.7)  # Light gray for blue category
    pdf.drawString(PDFLayout.MARGIN, y_after_image, f"Blue colors:  {total_blue}")

    draw_footer(pdf, width, 1)
